### ISSUE TITLE
COOK-3041 decide on proper management of msntauth.conf

### ISSUE THREAD

**Issue by juliandunn** [sous-chefs/squid#24]
Migrated @jtimberman's ticket from JIRA:

The squid cookbook default recipe currently deletes the msntauth.conf file. However, some environments may wish to have this managed by Chef.

http://stuff.mit.edu/afs/sipb/service/squid/build/auth_modules/MSNT/README.html

**Comment by Xorima** [comment]
Closing as old issue

If this still is an issue please open an new issue
