### ISSUE TITLE
Fails while fetching IP and netmask

### ISSUE THREAD

**Issue by manojbhatt** [sous-chefs/squid#86]
### Cookbook version
4.0.2

### Chef-client version
chef-12.21.3-1.el6.x86_64

### Platform Details
CentOS release 6.9 (Final) 
CloudPlatform : Azure

### Scenario:
Recipe intermittently fails while fetching the netmask 
https://github.com/chef-cookbooks/squid/blob/master/recipes/default.rb#L23

### Steps to Reproduce:
We have included the default recipe in one of our cookbook ( basically which setup NAT ) and running chef-client from bootstrap script ( which executes when server comes up for the very first time).

### Expected Result:
Squid recipe will fail. 

### Actual Result:
Don't have it handy right now. Will update once re-create the server.

**Comment by bcg62** [comment]
I am also seeing this. I think it happens when you have an interface thats up with no IP/mask

**Comment by bcg62** [comment]
node['squid']['listen_interface'] is detecting the first up interface.  

`default['squid']['listen_interface'] = node['network']['interfaces'].dup.reject { |k, v| k == 'lo' || v[:state] == 'down' }.keys.first`

On a machine with multiple interfaces, this will not always be the interface holding `node['squid']['ipaddress']`

**Comment by bcg62** [comment]
something like this works

```
default['squid']['ipaddress'] = node['ipaddress']
node['network']['interfaces'].each do |name, info|
  next unless info['addresses'].keys.include?(node['squid']['ipaddress'])
  default['squid']['listen_interface'] = name
end
```

**Comment by manojbhatt** [comment]
I again saw this issue 

Here is the error trace :
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/es_nat/recipes/default.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/squid/recipes/default.rb:26:in `from_file'
 

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/squid/recipes/default.rb:

```
 19:  # limitations under the License.
 20:  #
 21:  
 22:  # variables
 23:  ipaddress = node['squid']['ipaddress']
 24:  listen_interface = node['squid']['listen_interface']
 25:  version = node['squid']['version']
 **26>> netmask = node['network']['interfaces'][listen_interface]['addresses'][ipaddress]['netmask']**
 27:  
 28:  # squid/libraries/default.rb
 29:  acls = squid_load_acls
 30:  host_acl = squid_load_host_acl
 31:  url_acl = squid_load_url_acl
 32:  
 33:  # Log variables to Chef::Log::debug()
 34:  Chef::Log.debug("Squid listen_interface: #{listen_interface}")
 35:  Chef::Log.debug("Squid ipaddress: #{ipaddress}")

```

**Comment by huckley** [comment]
I think the whole netmask is not necessary, because i can not detect any line where it is used.
It also makes trouble is I start bind on a non local ip. (via echo 1 >/proc/sys/net/ipv4/ip_nonlocal_bind)
